/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Demo */

#ifndef _Included_Demo
#define _Included_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Demo
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Demo_square
  (JNIEnv *, jobject, jint);

/*
 * Class:     Demo
 * Method:    reverse
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Demo_reverse
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Demo
 * Method:    upper
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Demo_upper
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Demo
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Demo_sum
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
